from autotest import autotest
#from logicversions import logic
autotest.autotest('XRPUSDT')
autotest.autotest('BNBUSDT')
autotest.autotest('LINKUSDT')
autotest.autotest('BTCUSDT')
autotest.autotest('ICPUSDT')
autotest.autotest('DOTUSDT')
autotest.autotest('DOGEUSDT')
autotest.autotest('APEUSDT')
autotest.autotest('FILUSDT')
autotest.autotest('SOLUSDT')
autotest.autotest('WAVESUSDT')
autotest.autotest('ADAUSDT')
autotest.autotest('ETHUSDT')
autotest.autotest('GMTUSDT')
autotest.autotest('KLAYUSDT')
autotest.autotest('MANAUSDT')
autotest.autotest('MKRUSDT')
autotest.autotest('1000SHIBUSDT')
autotest.autotest('TLMSHIBUSDT')
